version: '3.8'

services:
  atm10-neoforge:
    build: .
    container_name: atm10-neoforge
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./mods:/minecraft/mods
      - ./config:/minecraft/config
      - ./world:/minecraft/world
    restart: unless-stopped
    stdin_open: true
    tty: true