version: '4.4'

services:
  atm10:
    image: my-atm10-server
    container_name: atm10-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data/world:/minecraft/server-files/world
      - ./data/logs:/minecraft/server-files/logs
      - ./data/server.properties:/minecraft/server-files/server.properties
      - ./data/eula.txt:/minecraft/server-files/eula.txt
      - ./data/ops.json:/minecraft/server-files/ops.json
      - ./data/journeymap:/minecraft/server-files/journeymap
      - ./data/local:/minecraft/server-files/local
      - ./data/packmenu:/minecraft/server-files/packmenu
      - ./data/patchouli_books:/minecraft/server-files/patchouli_books
      # Добавляйте другие папки/файлы по необходимости
    environment:
      MEMORY: "10G"  # Опционально, регулирует выделяемую память для Java
